global:
  resolve_timeout: 5m
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

route:
  group_by: ['namespace', 'alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'pagerduty-critical'
  routes:
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
    - match:
        severity: warning
      receiver: 'pagerduty-warning'
    - match:
        severity: info
      receiver: 'slack-notifications'
    - match:
        alertname: Watchdog
      receiver: 'null'

receivers:
  - name: 'null'
  
  - name: 'pagerduty-critical'
    pagerduty_configs:
      - service_key: ${pagerduty_service_key}
        send_resolved: true
        severity: critical
        description: '{{ template "pagerduty.default.description" . }}'
        details:
          severity: '{{ .CommonLabels.severity }}'
          environment: '{{ .CommonLabels.environment }}'
          cluster: '{{ .CommonLabels.cluster }}'
          namespace: '{{ .CommonLabels.namespace }}'
          summary: '{{ .CommonAnnotations.summary }}'
          description: '{{ .CommonAnnotations.description }}'
  
  - name: 'pagerduty-warning'
    pagerduty_configs:
      - service_key: ${pagerduty_service_key}
        send_resolved: true
        severity: warning
        description: '{{ template "pagerduty.default.description" . }}'
        details:
          severity: '{{ .CommonLabels.severity }}'
          environment: '{{ .CommonLabels.environment }}'
          cluster: '{{ .CommonLabels.cluster }}'
          namespace: '{{ .CommonLabels.namespace }}'
          summary: '{{ .CommonAnnotations.summary }}'
          description: '{{ .CommonAnnotations.description }}'
  
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
        channel: '#dota-companion-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        footer: '{{ template "slack.default.footer" . }}'
        icon_emoji: ':rotating_light:'
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'namespace', 'instance']

templates:
  - '/etc/alertmanager/config/*.tmpl'
