loki:
  auth_enabled: false
  
  persistence:
    enabled: true
    storageClassName: standard
    size: ${loki_storage}
  
  serviceMonitor:
    enabled: true
    labels:
      monitoring: prometheus
  
  config:
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h  # 14 days
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

promtail:
  enabled: true
  
  serviceMonitor:
    enabled: true
    labels:
      monitoring: prometheus
  
  config:
    snippets:
      pipelineStages:
        - docker: {}
        - cri: {}
        - json:
            expressions:
              timestamp: time
              level: level
              message: message
              logger: logger
              trace_id: trace_id
        - timestamp:
            source: timestamp
            format: RFC3339Nano
        - labels:
            level:
            logger:
            trace_id:
        - output:
            source: message
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
